<?php

namespace SoftwareFeedBundle\Repository;

/**
 * SoftwareTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftwareTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
